//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMapping.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int Id { get; set; }
        public int EmpUserId { get; set; }
        public Nullable<System.DateTime> SignInDate { get; set; }
        public Nullable<System.DateTime> SignOutDate { get; set; }
        public double TotalHours { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
