//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMapping.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectUser
    {
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public int ProjectId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastAssignDate { get; set; }
        public Nullable<int> CreatorId { get; set; }
    
        public virtual ProjectRole ProjectRole { get; set; }
        public virtual Project Project { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
